uid: 86da9f5a-247c-4483-923a-4450a1162062
info:
  name: Get Audit Config
  type: http
  seq: 4
http:
  method: GET
  url: '{{base_url}}/api/v1/audit/config'
  auth:
    type: bearer
    token: '{{token}}'
