name: local
variables:
- name: base_url
  value: http://localhost:8774
- name: token
  value: ''
- name: username
  value: admin
- name: password
  value: admin123
- name: totp_code
  value: '533173'
- name: ca_cert_id
  value: ''
- name: token,
  value: ''
- name: totp_code
  value: '230913'
- name: policy_id
  value: ''
- name: user_id
  value: ''
