name: local
variables:
- name: base_url
  value: https://api.rocketvault.numericlabs.io
- name: username
  value: admin
- name: password
  value: admin123
- name: totp_code
  value: '310146'
- name: vault_name
  value: my-vault
- name: ca_cert_id
  value: ''
- name: token
  value: eyJhbGciOiJFUzI1NiIsImtpZCI6ImMzOWU1YTlkYjIxMGQyOWQiLCJ0eXAiOiJKV1QifQ.eyJ1c2VyX2lkIjoiNDY0M2RiYTktY2U1Ni00MjQ5LTgyMDYtMTY5MGFmY2U4MDViIiwidXNlcm5hbWUiOiJhZG1pbiIsInJvbGVzIjpbImFkbWluIl0sInN1YiI6IjQ2NDNkYmE5LWNlNTYtNDI0OS04MjA2LTE2OTBhZmNlODA1YiIsImF1ZCI6WyJQQVNTV09SRF9NQU5BR0VSIl0sImV4cCI6MTc4OTkzNzYwMiwibmJmIjoxNzg5OTM0MDAyLCJpYXQiOjE3ODk5MzQwMDIsImp0aSI6IjMxYjBlNjRjLTZjZTEtNDcxMC05ZGY1LTI0ODViNTk1OTgxYiJ9.waQka64ag-mHz96l1LIuNNYyI_jnEKpyeDsjXsyY2FNLhN5Heb-Ubn3hChK9fT_pMrR5I-b4k5kJxDnxdvOWLA
- name: password,
  value: ''
- name: refresh_token
  value: 338edb23877abbd30fc9051592afd097d605302b10859727c8927e53f8c57192
