name: local
variables:
- name: base_url
  value: http://localhost:8774
- name: token
  value: eyJhbGciOiJSUzI1NiIsImtpZCI6IjlkMWM3NTVmMDRkZGJjZmMiLCJ0eXAiOiJKV1QifQ.eyJ1c2VyX2lkIjoiMjE5Yjc4ZWMtMDg5Zi00YzcxLTgzOGQtZDIyMzkxMGJhMjU4IiwidXNlcm5hbWUiOiJ1c2VyMTRAZXhjaGFuZ2U0YWxsLmxvY2FsIiwicm9sZSI6InNlY3JldHNfbWFuYWdlciIsImlzcyI6Imh0dHBzOi8vbnVtZXJpY2xhYnMubHhkIiwic3ViIjoiMjE5Yjc4ZWMtMDg5Zi00YzcxLTgzOGQtZDIyMzkxMGJhMjU4IiwiYXVkIjpbIlBBU1NXT1JEX01BTkFHRVIiXSwiZXhwIjoxNzg2NzczMTEzLCJuYmYiOjE3ODY3Njk1MTMsImlhdCI6MTc4Njc2OTUxMywianRpIjoiNTAzNmM0NmUtYjY1My00ZGY1LWFjNGUtMmExMjUzOGU1MTdlIn0.GyUBPkNNK4_qQ8c9JNQ9KpEG7zl1yT_jjgjF8O5RgmPbG4G29O4HBXi-avYVrUOM_fQTLeNe_wA7WtB3AYeq3IMgYaoCjw4PdZfUcY_93U-70K6zV2Xvod780a5jNk2g5LbzK0H3NMm24pmucQLUY9Jz_z_hclh2v78nCxFUFbraEzOfh6GdT1wOl13Zh6eMdMKR7qtOy0W4mEA-KF4B32xC3QDhmatthWSGWi6PsvjFByy0sd5475PpoRTqivm_6gn6L6oz278jOaqzVo6TwQogYXD4yh8hwqb0uw7PoJD1LWwkuMeqhs5QNovp7vLHDfXABr-EImwYM0qiam-j6A
- name: username
  value: admin
- name: password
  value: admin123
- name: vault_name
  value: default
- name: ca_cert_id
  value: ''
- name: token,
  value: ''
- name: password,
  value: ''
- name: totp_code
  value: '297947'
