name: local
variables:
- name: base_url
  value: http://localhost:8774
- name: token
  value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNzNmMTZjOTUtNmQ2ZS00NmYyLWJjNTgtYjNkMmE3ZTUzZTFhIiwidXNlcm5hbWUiOiJjb25zdW1lci10ZXN0Iiwicm9sZSI6InNlcnZpY2VfYWNjb3VudCIsImlzcyI6Imh0dHA6Ly9sb2NhbGhvc3Q6ODc3NCIsInN1YiI6IjczZjE2Yzk1LTZkNmUtNDZmMi1iYzU4LWIzZDJhN2U1M2UxYSIsImF1ZCI6WyJQQVNTV09SRF9NQU5BR0VSIl0sImV4cCI6MTc3OTQyMzkwMiwibmJmIjoxNzc5NDIwMzAyLCJpYXQiOjE3Nzk0MjAzMDJ9.0_FNOzCSHk3EzgUj0rXppq4BFxQOJq8yH9jd3eAI-tA
- name: username
  value: admin
- name: password
  value: admin123
- name: totp_code
  value: '466791'
- name: refresh_token
  value: ca8ff9f4ed8c6ffb40a8ecf762431d4b768467f16cc51aa34c8487a900edb1a1
- name: password,
  value: ''
- name: secret_id
  value: af0f5e89-bacb-45a1-9d4c-2a607ed992d3
- name: service_account_id
  value: 414d984f-5f7f-455b-93fd-6a66a77c6746
- name: version
  value: '1'
- name: user_id
  value: 1e18149a-ea17-4549-8166-b07cf4225350
- name: request_page_size
  value: ''
- name: key_id
  value: ''
- name: certificate_id
  value: ''
